//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace ParcelViewer.org.larimer.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PropertyInformation.cfcSoapBinding", Namespace="http://webservices")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CFCInvocationException))]
    public partial class PropertyInformation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetImprovementsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBuildingIdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetParcelsPerAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPropertyInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PropertyInformation() {
            this.Url = global::ParcelViewer.Properties.Settings.Default.ParcelViewer_org_larimer_www_PropertyInformation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetImprovementsCompletedEventHandler GetImprovementsCompleted;
        
        /// <remarks/>
        public event GetBuildingIdsCompletedEventHandler GetBuildingIdsCompleted;
        
        /// <remarks/>
        public event GetParcelsPerAddressCompletedEventHandler GetParcelsPerAddressCompleted;
        
        /// <remarks/>
        public event GetPropertyInfoCompletedEventHandler GetPropertyInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservices", ResponseNamespace="http://webservices")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetImprovementsReturn")]
        public ImprovementInfo GetImprovements(string scheduleNum, string parcelNum, string buildingId) {
            object[] results = this.Invoke("GetImprovements", new object[] {
                        scheduleNum,
                        parcelNum,
                        buildingId});
            return ((ImprovementInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetImprovementsAsync(string scheduleNum, string parcelNum, string buildingId) {
            this.GetImprovementsAsync(scheduleNum, parcelNum, buildingId, null);
        }
        
        /// <remarks/>
        public void GetImprovementsAsync(string scheduleNum, string parcelNum, string buildingId, object userState) {
            if ((this.GetImprovementsOperationCompleted == null)) {
                this.GetImprovementsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetImprovementsOperationCompleted);
            }
            this.InvokeAsync("GetImprovements", new object[] {
                        scheduleNum,
                        parcelNum,
                        buildingId}, this.GetImprovementsOperationCompleted, userState);
        }
        
        private void OnGetImprovementsOperationCompleted(object arg) {
            if ((this.GetImprovementsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetImprovementsCompleted(this, new GetImprovementsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservices", ResponseNamespace="http://webservices")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetBuildingIdsReturn")]
        public BuildingIds GetBuildingIds(string scheduleNum, string parcelNum) {
            object[] results = this.Invoke("GetBuildingIds", new object[] {
                        scheduleNum,
                        parcelNum});
            return ((BuildingIds)(results[0]));
        }
        
        /// <remarks/>
        public void GetBuildingIdsAsync(string scheduleNum, string parcelNum) {
            this.GetBuildingIdsAsync(scheduleNum, parcelNum, null);
        }
        
        /// <remarks/>
        public void GetBuildingIdsAsync(string scheduleNum, string parcelNum, object userState) {
            if ((this.GetBuildingIdsOperationCompleted == null)) {
                this.GetBuildingIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBuildingIdsOperationCompleted);
            }
            this.InvokeAsync("GetBuildingIds", new object[] {
                        scheduleNum,
                        parcelNum}, this.GetBuildingIdsOperationCompleted, userState);
        }
        
        private void OnGetBuildingIdsOperationCompleted(object arg) {
            if ((this.GetBuildingIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBuildingIdsCompleted(this, new GetBuildingIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservices", ResponseNamespace="http://webservices")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetParcelsPerAddressReturn")]
        public Parcels GetParcelsPerAddress(string streetNum, string streetDir, string streetName, string city, string streetNameSearchType) {
            object[] results = this.Invoke("GetParcelsPerAddress", new object[] {
                        streetNum,
                        streetDir,
                        streetName,
                        city,
                        streetNameSearchType});
            return ((Parcels)(results[0]));
        }
        
        /// <remarks/>
        public void GetParcelsPerAddressAsync(string streetNum, string streetDir, string streetName, string city, string streetNameSearchType) {
            this.GetParcelsPerAddressAsync(streetNum, streetDir, streetName, city, streetNameSearchType, null);
        }
        
        /// <remarks/>
        public void GetParcelsPerAddressAsync(string streetNum, string streetDir, string streetName, string city, string streetNameSearchType, object userState) {
            if ((this.GetParcelsPerAddressOperationCompleted == null)) {
                this.GetParcelsPerAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetParcelsPerAddressOperationCompleted);
            }
            this.InvokeAsync("GetParcelsPerAddress", new object[] {
                        streetNum,
                        streetDir,
                        streetName,
                        city,
                        streetNameSearchType}, this.GetParcelsPerAddressOperationCompleted, userState);
        }
        
        private void OnGetParcelsPerAddressOperationCompleted(object arg) {
            if ((this.GetParcelsPerAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetParcelsPerAddressCompleted(this, new GetParcelsPerAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservices", ResponseNamespace="http://webservices")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetPropertyInfoReturn")]
        public PropertyInfo GetPropertyInfo(string scheduleNum, string parcelNum) {
            object[] results = this.Invoke("GetPropertyInfo", new object[] {
                        scheduleNum,
                        parcelNum});
            return ((PropertyInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetPropertyInfoAsync(string scheduleNum, string parcelNum) {
            this.GetPropertyInfoAsync(scheduleNum, parcelNum, null);
        }
        
        /// <remarks/>
        public void GetPropertyInfoAsync(string scheduleNum, string parcelNum, object userState) {
            if ((this.GetPropertyInfoOperationCompleted == null)) {
                this.GetPropertyInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPropertyInfoOperationCompleted);
            }
            this.InvokeAsync("GetPropertyInfo", new object[] {
                        scheduleNum,
                        parcelNum}, this.GetPropertyInfoOperationCompleted, userState);
        }
        
        private void OnGetPropertyInfoOperationCompleted(object arg) {
            if ((this.GetPropertyInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPropertyInfoCompleted(this, new GetPropertyInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://webservices")]
    public partial class ImprovementInfo {
        
        private string basementFinishedSquareFeetField;
        
        private string basementSquareFeetField;
        
        private string bathsField;
        
        private string bedroomsField;
        
        private string builtAsField;
        
        private string classDescrField;
        
        private string conditionField;
        
        private string condoSquareFeetField;
        
        private string exteriorField;
        
        private string foundationField;
        
        private string garageSquareFeetField;
        
        private string hvacField;
        
        private string interiorField;
        
        private string messageField;
        
        private string occupancyField;
        
        private string propertyTypeField;
        
        private string qualityField;
        
        private string roofCoverField;
        
        private string roofTypeField;
        
        private string roomsField;
        
        private string squareFeetField;
        
        private System.Nullable<double> statusField;
        
        private string storiesField;
        
        private string unitTypeField;
        
        private string unitsField;
        
        private string yearBuiltField;
        
        private string yearRemodelField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string basementFinishedSquareFeet {
            get {
                return this.basementFinishedSquareFeetField;
            }
            set {
                this.basementFinishedSquareFeetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string basementSquareFeet {
            get {
                return this.basementSquareFeetField;
            }
            set {
                this.basementSquareFeetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string baths {
            get {
                return this.bathsField;
            }
            set {
                this.bathsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bedrooms {
            get {
                return this.bedroomsField;
            }
            set {
                this.bedroomsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string builtAs {
            get {
                return this.builtAsField;
            }
            set {
                this.builtAsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string classDescr {
            get {
                return this.classDescrField;
            }
            set {
                this.classDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string condoSquareFeet {
            get {
                return this.condoSquareFeetField;
            }
            set {
                this.condoSquareFeetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string exterior {
            get {
                return this.exteriorField;
            }
            set {
                this.exteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string foundation {
            get {
                return this.foundationField;
            }
            set {
                this.foundationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string garageSquareFeet {
            get {
                return this.garageSquareFeetField;
            }
            set {
                this.garageSquareFeetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hvac {
            get {
                return this.hvacField;
            }
            set {
                this.hvacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string interior {
            get {
                return this.interiorField;
            }
            set {
                this.interiorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string occupancy {
            get {
                return this.occupancyField;
            }
            set {
                this.occupancyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string propertyType {
            get {
                return this.propertyTypeField;
            }
            set {
                this.propertyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string roofCover {
            get {
                return this.roofCoverField;
            }
            set {
                this.roofCoverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string roofType {
            get {
                return this.roofTypeField;
            }
            set {
                this.roofTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rooms {
            get {
                return this.roomsField;
            }
            set {
                this.roomsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string squareFeet {
            get {
                return this.squareFeetField;
            }
            set {
                this.squareFeetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string stories {
            get {
                return this.storiesField;
            }
            set {
                this.storiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string unitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string yearBuilt {
            get {
                return this.yearBuiltField;
            }
            set {
                this.yearBuiltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string yearRemodel {
            get {
                return this.yearRemodelField;
            }
            set {
                this.yearRemodelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.xml.coldfusion")]
    public partial class CFCInvocationException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://webservices")]
    public partial class PropertyInfo {
        
        private string accountTypeField;
        
        private string addressField;
        
        private string cityField;
        
        private string lastSaleDateField;
        
        private System.Nullable<double> lastSalePriceField;
        
        private string legalField;
        
        private System.Nullable<double> lotSizeField;
        
        private string mailAddress1Field;
        
        private string mailAddress2Field;
        
        private string mailCityField;
        
        private string mailStateField;
        
        private string mailZipCodeField;
        
        private string messageField;
        
        private string ownerName1Field;
        
        private string ownerName2Field;
        
        private string parcelNumberField;
        
        private string scheduleNumberField;
        
        private System.Nullable<double> statusField;
        
        private string subdivDescrField;
        
        private string subdivIdField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string accountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastSaleDate {
            get {
                return this.lastSaleDateField;
            }
            set {
                this.lastSaleDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> lastSalePrice {
            get {
                return this.lastSalePriceField;
            }
            set {
                this.lastSalePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string legal {
            get {
                return this.legalField;
            }
            set {
                this.legalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> lotSize {
            get {
                return this.lotSizeField;
            }
            set {
                this.lotSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mailAddress1 {
            get {
                return this.mailAddress1Field;
            }
            set {
                this.mailAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mailAddress2 {
            get {
                return this.mailAddress2Field;
            }
            set {
                this.mailAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mailCity {
            get {
                return this.mailCityField;
            }
            set {
                this.mailCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mailState {
            get {
                return this.mailStateField;
            }
            set {
                this.mailStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mailZipCode {
            get {
                return this.mailZipCodeField;
            }
            set {
                this.mailZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ownerName1 {
            get {
                return this.ownerName1Field;
            }
            set {
                this.ownerName1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ownerName2 {
            get {
                return this.ownerName2Field;
            }
            set {
                this.ownerName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string parcelNumber {
            get {
                return this.parcelNumberField;
            }
            set {
                this.parcelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string scheduleNumber {
            get {
                return this.scheduleNumberField;
            }
            set {
                this.scheduleNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string subdivDescr {
            get {
                return this.subdivDescrField;
            }
            set {
                this.subdivDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string subdivId {
            get {
                return this.subdivIdField;
            }
            set {
                this.subdivIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://webservices")]
    public partial class Parcels {
        
        private string messageField;
        
        private object[] parcelField;
        
        private System.Nullable<double> statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object[] parcel {
            get {
                return this.parcelField;
            }
            set {
                this.parcelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://webservices")]
    public partial class BuildingIds {
        
        private object[] buildingField;
        
        private string messageField;
        
        private System.Nullable<double> statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object[] building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<double> status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetImprovementsCompletedEventHandler(object sender, GetImprovementsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetImprovementsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetImprovementsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImprovementInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImprovementInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetBuildingIdsCompletedEventHandler(object sender, GetBuildingIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBuildingIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBuildingIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BuildingIds Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BuildingIds)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetParcelsPerAddressCompletedEventHandler(object sender, GetParcelsPerAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetParcelsPerAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetParcelsPerAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Parcels Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Parcels)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPropertyInfoCompletedEventHandler(object sender, GetPropertyInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPropertyInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPropertyInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PropertyInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PropertyInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591